### ISSUE TITLE
uploadOnSave not working

### ISSUE THREAD

**Issue by mmolnar** [dingjie/atom-sync#12]
I am unable to get this feature to work in recent versions of atom.

**Comment by mattgiles** [comment]
any chance this will be resolved for newer versions of atom?

**Comment by dingjie** [comment]
I'll be working on this today after long leaving.

**Comment by dingjie** [comment]
try upgrading to [0.6.0](https://github.com/dingjie/atom-sync/releases/tag/v0.6.0)

**Comment by mattgiles** [comment]
awesome!
