### ISSUE TITLE
enhancement: run command after sync

### ISSUE THREAD

**Issue by wasche** [dingjie/atom-sync#13]
I love using this to sync files to my server after editing, but sometimes I need to run a build command afterward in order for the server to pick up the change (like less -> css), so I'd like to be able to eliminate that middle step so I can just alt+tab between atom and the browser.

**Comment by dsoares** [comment]
I've made a PR with this enhancement if you're still interested. See PR https://github.com/dingjie/atom-sync/pull/28.

**Comment by dingjie** [comment]
Upgrade to 0.7.0 and try the new "Trigger"
