### ISSUE TITLE
Feature: key file

### ISSUE THREAD

**Issue by markentingh** [dingjie/atom-sync#22]
I have to use a pem key file when connecting to my AWS EC2 instance via SSH. How can I include the pem file in your extension config?

**Comment by dingjie** [comment]
here's my config for ec2 in ~/.ssh/config
![qq20160125-0 2x](https://cloud.githubusercontent.com/assets/586262/12537423/def6c278-c2f9-11e5-9233-2f90283d260b.png)

**Comment by markentingh** [comment]
hmm... I am using Windows, there is a .sync-config.cson file in the project folder that is used by atom-sync. The file contains something like this:

    remote:
      host: "******.us-west-2.compute.amazonaws.com"
      user: "ec2-user"
      path: "/var/www/html/"
    behaviour:
      uploadOnSave: true
      syncDownOnOpen: true
      forgetConsole: false
      autoHideConsole: true
      alwaysSyncAll: false
    option:
      deleteFiles: false
      exclude: [
        ".sync-config.cson"
        ".git"
        "node_modules"
        "tmp"
        "vendor"
        "var"
        "media"
      ]

Is there a setting in the config that I can add to link my pem file?
