### ISSUE TITLE
Atom sync seems to be broke after upgrade of atom

### ISSUE THREAD

**Issue by tinpotnick** [dingjie/atom-sync#63]
Atom recently updated to 1.17.1 but the menus for Atom Sync have disappeared even though Atom sync is installed.

When you save an individual file this still works, just no menu when you right click on the file tree.

This is on a Mac.

**Comment by microwavenby** [comment]
Duplicate of https://github.com/dingjie/atom-sync/issues/61

**Comment by tinpotnick** [comment]
Ah, sorry yes. Found and used it to fix.
