### ISSUE TITLE
Option to always sync from root directory

### ISSUE THREAD

**Issue by svanegaard** [dingjie/atom-sync#7]
Thank you for a very nice plugin!

I am wondering if you can possibly add an option to always sync the project entire projekt when saving a file (uploadOnSave).

If I am working on a file in a sub folder, the plugin only syncs that sub folder. It would be nice to have an option in the config file (.sync-config.cson) to always sync the entire projekt to the remote server, no matter where the saved file is located in the project.

I hope you understand what I mean. If not, I will gladly elaborate!

**Comment by dingjie** [comment]
Sounds great! I'll be working on this soon.

**Comment by dingjie** [comment]
svanegaard, thanks for your suggestion. You can try v0.5.0 now for the new feature.
Just add ```alwaysSyncAll: true``` into ```behaviour``` section in ```.sync-config.cson``` and enjoy coding :)

**Comment by dingjie** [comment]
Found an issue #8, will fix it later.

**Comment by svanegaard** [comment]
Thank you for the quick fix. It seems to work perfectly for me. :thumbsup:

The only small issue is that it seems that I had to restart Atom before the changes in the config file started to work. I have not been using Atom for long, so I am not sure if it is a bug in Atom or in the plugin.
